In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
import matplotlib.style as style
import warnings
warnings.filterwarnings('ignore')

# store elements as dictionary keys and their counts as dictionary values
from collections import Counter

In [2]:
data = pd.read_csv("data_diabetes2.csv")
#data.drop(['id'], axis=1, inplace=True)
df = data.copy()

In [3]:
df.head()

case2_diabet arthritis gout thyroid chronic_bronchitis abdominal_pain  \
0  prediabet/undiag       yes   no      no                 no             no   
1        not_diabet       NaN  NaN     NaN                NaN            NaN   
2  prediabet/undiag       yes   no      no                 no             no   
3  prediabet/undiag       yes   no     yes                 no             no   
4  prediabet/undiag        no   no      no                 no             no   

  gallstones diabetic_relative overweight high_bp  ... creatinine_mg/dL  \
0         no               yes        yes     yes  ...             0.92   
1        NaN               NaN         no      no  ...             0.81   
2         no               yes        yes     yes  ...             0.58   
3        yes               yes        yes     yes  ...             1.32   
4         no                no         no      no  ...             1.13   

   globulin_g/dL  glucose_mg/dL  potassium_mmol/L  sodium_mmol/L  \
0            2.9           85.0               4.0          141.0   
1            2.7           94.0               4.4          144.0   
2            3.2          116.0               4.4          144.0   
3            3.3           96.0               4.1          141.0   
4            3.1           98.0               4.9          140.0   

   calcium_mg/dL  triglycerides_mg/dL uricacid_mg/dL  \
0            9.2                 95.0            5.8   
1            9.6                 92.0            8.0   
2            9.5                 72.0            4.5   
3            9.9                132.0            6.2   
4            9.4                 59.0            4.2   

  vigorous_recreational_activities  minutes_sedentary_activity  
0                               no                       300.0  
1                               no                       240.0  
2                               no                       120.0  
3                               no                       600.0  
4                              yes                       420.0  

[5 rows x 51 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5478 entries, 0 to 5477
Data columns (total 51 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   case2_diabet                      4640 non-null   object 
 1   arthritis                         5195 non-null   object 
 2   gout                              5203 non-null   object 
 3   thyroid                           5195 non-null   object 
 4   chronic_bronchitis                5204 non-null   object 
 5   abdominal_pain                    5205 non-null   object 
 6   gallstones                        5197 non-null   object 
 7   diabetic_relative                 5219 non-null   object 
 8   overweight                        5477 non-null   object 
 9   high_bp                           5478 non-null   object 
 10  high_chol                         5472 non-null   object 
 11  pulse_60                          5218 non-null   float64
 12  systol

In [5]:
df = data[['case2_diabet', 'arthritis', 'overweight', 'high_bp', 'high_chol',
       'systolic', 'bmi', 'WH_ratio', 'head%_fat', 'glucose_mg/dL',
       'vigorous_recreational_activities']]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5478 entries, 0 to 5477
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   case2_diabet                      4640 non-null   object 
 1   arthritis                         5195 non-null   object 
 2   overweight                        5477 non-null   object 
 3   high_bp                           5478 non-null   object 
 4   high_chol                         5472 non-null   object 
 5   systolic                          4848 non-null   float64
 6   bmi                               5379 non-null   float64
 7   WH_ratio                          5128 non-null   float64
 8   head%_fat                         5478 non-null   float64
 9   glucose_mg/dL                     5105 non-null   float64
 10  vigorous_recreational_activities  5478 non-null   object 
dtypes: float64(5), object(6)
memory usage: 470.9+ KB


In [6]:
df.dropna(inplace=True)
df.reset_index(inplace=True, drop=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3495 entries, 0 to 3494
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   case2_diabet                      3495 non-null   object 
 1   arthritis                         3495 non-null   object 
 2   overweight                        3495 non-null   object 
 3   high_bp                           3495 non-null   object 
 4   high_chol                         3495 non-null   object 
 5   systolic                          3495 non-null   float64
 6   bmi                               3495 non-null   float64
 7   WH_ratio                          3495 non-null   float64
 8   head%_fat                         3495 non-null   float64
 9   glucose_mg/dL                     3495 non-null   float64
 10  vigorous_recreational_activities  3495 non-null   object 
dtypes: float64(5), object(6)
memory usage: 300.5+ KB


#### Setting traget and features

In [7]:
random_state=101

In [8]:
df['case2_diabet'].replace({'not_diabet':0,'prediabet/undiag':1},inplace=True)
df.case2_diabet.value_counts()

1    1847
0    1648
Name: case2_diabet, dtype: int64

In [9]:
target = df['case2_diabet']
features = df.drop(['case2_diabet'], axis=1)

In [10]:
numerical =  df.drop(['case2_diabet'],axis=1).select_dtypes('number')
categorical = df.select_dtypes('object')

In [11]:
categorical.columns.values

array(['arthritis', 'overweight', 'high_bp', 'high_chol',
       'vigorous_recreational_activities'], dtype=object)

In [12]:
features = pd.get_dummies(data=features, columns=categorical.columns.values, drop_first=True)

In [13]:
### Default Parameter
from sklearn.model_selection import train_test_split
#### split data
X_train, X_test, y_train, y_test = train_test_split(features, target, 
                                                    random_state=random_state, stratify=target)

In [14]:
# Print number of observations in X_train, X_test, y_train, and y_test
print(len(X_train), len(X_test), len(y_train), len(y_test))

2621 874 2621 874


#### Modelling

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, recall_score
from sklearn.metrics import roc_auc_score,roc_curve

In [16]:
from sklearn.svm import SVC
svm_model = SVC(kernel = "linear",random_state=random_state).fit(X_train, y_train)
y_pred = svm_model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('----------------------------------------')
print(classification_report(y_test, y_pred))

[[309 103]
 [104 358]]
----------------------------------------
              precision    recall  f1-score   support

           0       0.75      0.75      0.75       412
           1       0.78      0.77      0.78       462

    accuracy                           0.76       874
   macro avg       0.76      0.76      0.76       874
weighted avg       0.76      0.76      0.76       874



In [17]:
model = SVC(C=2e-06,kernel='linear', probability=True).fit(X_train, y_train)

y_pred = model.predict(X_train)
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))
print('----------------------------------------')
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 559  677]
 [ 140 1245]]
              precision    recall  f1-score   support

           0       0.80      0.45      0.58      1236
           1       0.65      0.90      0.75      1385

    accuracy                           0.69      2621
   macro avg       0.72      0.68      0.67      2621
weighted avg       0.72      0.69      0.67      2621

----------------------------------------
[[171 241]
 [ 39 423]]
              precision    recall  f1-score   support

           0       0.81      0.42      0.55       412
           1       0.64      0.92      0.75       462

    accuracy                           0.68       874
   macro avg       0.73      0.67      0.65       874
weighted avg       0.72      0.68      0.66       874



In [18]:
prediction_proba = model.predict_proba(X_test)

In [19]:
prediction_proba

array([[0.24303655, 0.75696345],
       [0.31837832, 0.68162168],
       [0.67201083, 0.32798917],
       ...,
       [0.35358992, 0.64641008],
       [0.10351828, 0.89648172],
       [0.87277449, 0.12722551]])

In [20]:
y_test

2513    1
806     1
2505    1
3130    1
1550    1
       ..
330     1
1249    1
481     1
1001    0
3221    0
Name: case2_diabet, Length: 874, dtype: int64

## Export Model / Deployment Model

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3495 entries, 0 to 3494
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   case2_diabet                      3495 non-null   int64  
 1   arthritis                         3495 non-null   object 
 2   overweight                        3495 non-null   object 
 3   high_bp                           3495 non-null   object 
 4   high_chol                         3495 non-null   object 
 5   systolic                          3495 non-null   float64
 6   bmi                               3495 non-null   float64
 7   WH_ratio                          3495 non-null   float64
 8   head%_fat                         3495 non-null   float64
 9   glucose_mg/dL                     3495 non-null   float64
 10  vigorous_recreational_activities  3495 non-null   object 
dtypes: float64(5), int64(1), object(5)
memory usage: 300.5+ KB


In [22]:
df.columns

Index(['case2_diabet', 'arthritis', 'overweight', 'high_bp', 'high_chol',
       'systolic', 'bmi', 'WH_ratio', 'head%_fat', 'glucose_mg/dL',
       'vigorous_recreational_activities'],
      dtype='object')

In [23]:
x_y = df[df.columns.values]

In [24]:
import pickle
import pandas as pd

In [25]:
filename = 'finalized_model2.sav'
pickle.dump(model, open(filename, 'wb'))

In [26]:
filename = 'x_dummies_column2.sav'
pickle.dump(features.columns, open(filename , 'wb'))

In [27]:
# filename = 'real_colomn.sav'
# pickle.dump(x_y.drop('Price',axis=1).columns, open(filename , 'wb'))

In [28]:
x_y.arthritis.unique()

array(['yes', 'no'], dtype=object)

In [29]:
x_y['overweight'].unique()

array(['yes', 'no'], dtype=object)

In [30]:
x_y['high_bp'].unique()

array(['yes', 'no'], dtype=object)

In [31]:
x_y['high_chol'].unique()

array(['no', 'yes'], dtype=object)

In [32]:
model = pickle.load(open('finalized_model2.sav','rb'))
# real_columns = pickle.load(open('real_colomn.sav','rb'))
one_hot_columns = pickle.load(open('x_dummies_column2.sav','rb'))

def prediction(data):
    df = pd.DataFrame(data,index=[0])
    df = pd.get_dummies(df)
    df = df.reindex(columns=one_hot_columns, )
    hasil = model.predict(df)
    return round(hasil[0])

In [33]:
df.iloc[1,:]

case2_diabet                           1
arthritis                             no
overweight                            no
high_bp                               no
high_chol                            yes
systolic                             108
bmi                                 21.3
WH_ratio                            0.95
head%_fat                           23.5
glucose_mg/dL                         98
vigorous_recreational_activities     yes
Name: 1, dtype: object

In [34]:
inputan = {'arthritis': 'yes', 'overweight': 'yes', 'high_bp': 'yes', 'high_chol': 'no',
           'systolic':108,'bmi':31.7,'glucose_mg/dL':98, 'WH_ratio':0.93,'head%_fat':23.5,'vigorous_recreational_activities': 'no'}

In [35]:
df = pd.DataFrame(inputan,index=[0])
# one hot encoding (categorical item berubah menjadi numerical item (columns))
df = pd.get_dummies(df)
df = df.reindex(columns=one_hot_columns, fill_value=0)
hasil_prediction = model.predict(df)
print(f'Hasil prediksi : {hasil_prediction[0]}')
probability = model.predict_proba(df)
print(f'Hasil proba : {probability}')

Hasil prediksi : 1
Hasil proba : [[0.66133419 0.33866581]]


In [36]:
probability[0,1]

0.33866580519704226

In [37]:
if probability[0,1] < 0.3:
    print('You are in Low Risk prediabetes/ undiagnose diabetes')
elif probability[0,1] < 0.6:
    print('You are in Moderate Risk prediabetes/ undiagnose diabetes')
else:
    print('You are in High Risk prediabetes/ undiagnose diabetes')

You are in Moderate Risk prediabetes/ undiagnose diabetes
